---
# tasks file for mysql_db
       -   
         name: Install MySQL database
         apt: name={{item}} state=installed
         with_items:
              - mysql-server
              - mysql-client

       -
        name: Start MySQL Service
        service: name=mysql state=started enabled=yes

       -
        name: Create database user
        mysql_user:
                name: "{{ db_user }}"
                password: "{{ db_user_password }}"
                priv: '*.*:ALL'
                state: present

       -
        name: Create database
        mysql_db: name={{ db_name }} state=present
